config/routes.rb
Rails.application.routes.draw do
   resources :categories, only:[:show]
   resources :ads, only:[:show, :new, :create]
   resources :users, only:[:show, :new, :create]
   resources :comments, only:[:new, :create]
   post "/search", to: "ads#search"
   get "/login", to: "sessions#new"
   post "/login", to: "sessions#create"
   delete "/logout", to: "sessions#destroy"
  root "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :renter, :class_name => 'User'
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ads, dependent: :destroy
  has_many :renters, :class_name => "User", through: :ads
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :rentee, :class_name => "User"
  belongs_to :ad
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ads, :foreign_key => 'renter_id'
    has_many :comments, :foreign_key => 'rentee_id'
    has_many :categories, through: :ads
    validates :user_name, presence: true, uniqueness: { case_sensitive: false }
    validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_secure_password

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :find_ad, only: :show

  def new
    @ad = Ad.new
    @categories = Category.all

  end

  def create
    @user = User.find(session[:user_id])
    @ad = Ad.new(ads_params)
    @ad.renter = @user
    @ad.save
    redirect_to @ad
  end

  def show
    @categories = Category.all
    @comment = Comment.new
  end
  def search
    # byebug
    @categories = Category.all
    @ads = Ad.where("name LIKE ?", "%#{params[:q]}%")
  end

  private
  def find_ad
    @ad = Ad.find(params[:id])
  end

  def ads_params
    params.require(:ad).permit(:category_id, :item_description, :image_path, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: :show
  def index
    @categories = Category.all
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      @user = nil
    end
  end

  def show
    @categories = Category.all
  end

  private
  def find_category
    @category = Category.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
  @comment = Comment.new
end

def create
  @rentee = User.find(session[:user_id])
  @comment = Comment.new(comment_params)
  @comment.rentee = @rentee
  @comment.save
  redirect_to ad_path(comment_params[:ad_id])
end

private
def comment_params
  params.require(:comment).permit(:ad_id, :comment)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @categories = Category.all
  end
  def create
    # byebug
    if params[:session][:user_name].empty? || params[:session][:password].empty?
      flash[:errors] = "Username / Password cannot be blank!!!"
      redirect_to login_path
    else
      @user = User.find_by(user_name: params[:session][:user_name])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to @user
      else
        flash[:errors] = "Username/Password do not match"
        redirect_to login_path
      end
    end
  end
  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: :show

  def show
    @categories = Category.all

  end

  def new
    @categories = Category.all
    @user = User.new
  end

  def create
    # byebug
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :location, :password, :img_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/views/ads/_form.html.erb
<%=form_for @ad, class: "form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :name,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", id: "name", placeholder: "Item Name:" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :item_description,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :item_description, class: "form-control", id: "item_description", placeholder: "Item Description" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image_path,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :image_path, class: "form-control", id: "image_path", placeholder: "Link to Image:" %>
    </div>
  </div>

<div class="form-group">
  <%= f.label "Category",  class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.collection_select :category_id, @categories, :id, :name  %>
  </div>
</div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%=f.button "Post", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/ads/new.html.erb
<h2>Post an Ad</h2>
<%= render 'form' %>

app/views/ads/search.html.erb
  <h3>List of items:</h3>
<div class="row">
  <% @ads.each do |ad| %>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= link_to ad.name, ad %></h4>
        <img src=<%= ad.image_path %> class="img-thumbnail">
        <p class="card-text"><%= ad.item_description %></p>
        <a href="<%=ad_path(ad)%>" class="btn btn-primary">View Item</a>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/ads/show.html.erb
<h2><%= @ad.name %>
<br><small>Posted by <%= link_to @ad.renter.user_name, @ad.renter %></small></h2>
<ul>
  <img src= <%= @ad.image_path %> class="resize">
  <br><p class="lead"><%= @ad.item_description %></p>
<% @ad.comments.each do |review| %>
<li>"<%= review.comment %>" - <%= link_to review.rentee.user_name, review.rentee %></li>
<% end %>
</ul>
<% if !!session[:user_id] %>
<%= form_for @comment do |f| %>
<%= f.hidden_field :ad_id, :value => @ad.id %>
<%= f.label "Leave a Comment:" %>
<%= f.text_field :comment %>
<%= f.submit "Post" %>
<% end  %>
<% end %>

app/views/categories/index.html.erb
<h2>The Yellow Pages</h2>
<br>
<% if @user != nil %>
  <h5>Welcome <%=@user.user_name %>!</h5>
<% end %>


<div class="row">
  <% @categories.each do |category| %>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= link_to category.name, category %></h4>
        <p class="card-text"><%= category.description %></p>
        <a href="<%=category_path(category)%>" class="btn btn-primary">See ads</a>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<p>

  <div class="row">
<% @category.ads.each do |ad| %>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h4><%= link_to ad.name, ad %></h4>
        <img src=<%= ad.image_path %> class="img-thumbnail">
        <p class="card-text"><%= ad.item_description %></p>
        <a href="<%=ad_path(ad)%>" class="btn btn-primary">See item</a>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      /* .jumbotron {
        background-color:#FFDD00;
        color:black;
      } */
      /* Adds borders for tabs */
      .tab-content {
        border-left: 1px solid #ddd;
        border-right: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        padding: 10px;
      }
      .nav-tabs {
        margin-bottom: 0;
      }
    </style>
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <div class="navbar-brand" href="#">16bw</div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav">
                <li class=<%=active_class(root_path)%>><a href="/">Home<span class="sr-only">(current)</span></a></li>
                <% if !!session[:user_id] %>
                <li class=<%=active_class(new_ad_path)%>><a href=<%=new_ad_path%>>Post Ad</a></li>
                <% end %>
                <li class="dropdown">
                  <a href="# " class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% @categories.each do |category| %>
                    <li><a href="<%=category_path(category)%>"><%=category.name%></a></li>
                    <li role="separator" class="divider"></li>
                    <% end %>
                  </ul>
                </li>
              </ul>

              <%=form_tag("/search", method: "post", :class => "navbar-form navbar-left") do %>
                <div class="form-group">
                  <%=text_field_tag :q, "", class: 'form-control' %>
                </div>
                <%=submit_tag("Search", :class =>"btn btn-default")%>
              <% end %>
              <!-- need to evaluate if session is defined, if not then deactivate the below nav options -->
              <% if !!session[:user_id] %>
                <ul class="nav navbar-nav navbar-right">
                  <li class=<%=active_class(user_path(session[:user_id]))%>><a href="<%=user_path(session[:user_id])%>">My Profile<span class="sr-only">(current)</span></a></li>
                  <li><%=link_to "logout", logout_path(session[:user_id]), method: :delete%></li>
                </ul>
              <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li><%=link_to "login", login_path%></li>
              </ul>
              <% end %>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </div>
      <div class="jumbotron">
        <%= yield %>
      </div>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/_form.html.erb
<% if flash[:errors] %>
<ul class="errors">
  <% flash[:errors].each do |msg| %>
    <li><%=msg%></li>
  <% end %>
</ul>
<% end %>

<%=form_for @user, class: "form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :user_name,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user_name, class: "form-control", id: "user_name", placeholder: "Username" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", id: "email", placeholder: "Email" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, class: "form-control", id: "location", placeholder: "Location" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :img_path,  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :img_path, class: "form-control", id: "Profile Picture", placeholder: "Paste URL here" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control", id: "inputPassword3", placeholder: "Password" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%=f.button "Create Account", class: "btn btn-default" %>
    </div>
  </div>
<% end %>
<p class="text-center">Let's get some stuff!</p>

app/views/users/new.html.erb
<h3>Create a User</h3>

  <%= render 'form' %>

app/views/users/show.html.erb
<h2> <%= @user.user_name %> </h2><br>
<img src=<%= @user.img_path %> class="img-thumbnail" id="profile_pic">
<br>
<h3>About</h3>
<p><h4>Email:</h4><%= @user.email %>
<h4>Location:</h4> <%= @user.location %>


<h4><%= @user.user_name %>'s Ads:</h4>

<% @user.ads.each do |ad| %>
<%= link_to ad.name, ad %>
<% end %>

<h4>Recent Comments:</h4>
<% @user.comments.each do |review| %>
"<%= link_to review.comment, review.ad %>"
<% end %>